name: CI

on:
  # Acionar o fluxo de trabalho em eventos de push
  # ou pull request para a branch principal
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 
  build:
    # Configuração do trabalho de build
    runs-on: ubuntu-latest

    steps:
    # Configuração dos passos
    - uses: actions/checkout@v2
    # Configurar ambiente Node.js
    - name: Set up Node.js
      # Usa a ação oficial do Node.js para configurar o ambiente
      uses: actions/setup-node@v2
      with:
      # Especifica a versão do Node.js a ser utilizada
      node-version: ['14', '15', '16', '17', '18', '19', '20']
    - name: Install dependencies
      run: npm install
    - name: Install Cypress
      run: npm install Cypress -d
