name: CI
# Workflow para executar testes Cypress em pushes e pull requests na branch master
on:
  # Dispara o workflow em pull requests para a branch master
  push:
    # Dispara o workflow em pushes para a branch master
    branches:
      - master
  # Dispara o workflow em pull requests para a branch master
  pull_request:
    branches:
      - master

jobs:
  # Define o job de build
  build:
    # Define o ambiente de execução do job
    runs-on: ubuntu-latest
    # Define os passos do job
    strategy:
      # Define uma matriz de estratégias para o job
      matrix:
        # Define a versão do Node.js a ser usada
        node-version: [20.x]
    
    steps:
      # 1️⃣ Faz o checkout do código-fonte
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configura o Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Configura o registro do npm
          registry-url: https://registry.npmjs.org/
          # Configura a versão do Node.js
          node-version: ${{ matrix.node-version }}

      # 3️⃣ Instala dependências do projeto
      - name: Install dependencies
        run: npm install

      # 4️⃣ Instala o Cypress (opcional se já estiver no package.json)
      - name: Install Cypress
        run: npm install cypress --save-dev
      

      # 5️⃣ Executa os testes do Cypress (modo headless)
      - name: Run Cypress tests
        run: npx cypress run --headless
      #  Executa os testes do Cypress (modo headless) e coleta artefatos
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/videos/
          

